= AirWatch Service Status Checker v.1.0.4
Rasmus Sjorslev;
//:forceinclude:
:doctype: book
:icons: font
:source-highlighter: highlightjs
:toc: left
:toclevels: 4
:sectlinks:
//:snippets: ../../../target/generated-snippets

[introduction]
= Introduction

*THIS IS NOT SUPPORTED NOR ENDORSED BY AIRWATCH OR VMWARE SO USE AT YOUR OWN RISK*

[overview]
= Overview

Quick and dirty service to check ACC status as well as Directory settings. The service simply performs a form-based login to the Console like a regular user would and then performs AJAX calls for either ACC or Directory Settings status just like the console client would and returns the JSON response.

There is currently little to no error checking and the properties required are not verified to exist to please use the /status/props endpoints to verify manually once the service is running.

= Setup

NOTE: Currently this requires an account with Console Administrator permissions as i have not tested with any other roles.

A couple of properties are required for this to work properly. They are:

[source]
aw.url.tenant=https://TENANT-URL
aw.login.user=USERNAME
aw.login.password=PASSWORD
logging.level.com.example=DEBUG (Optional, but recommended for initial setup)

They can be set by editing the application.properties located at `/etc/runner/config/props/application.properties` on the Virtual Machine. +
This file gets mapped into the docker container using volumes so it is read by the Spring context upon launch.


[overview-http-verbs]
== HTTP Verbs

|===
| Verb | Usage

| `GET`
| Used to retrieve a status response for either a named service or all monitored services.

| `POST`
| Used to create a new resource

|===

[http-status-codes]
== HTTP Status Codes

|===
| Status code | Usage

| `200 OK`
| Standard response for successful HTTP requests.

| `400 Bad Request`
| The server cannot or will not process the request due to something that is perceived to be a client error
    (e.g., malformed request syntax, invalid request message framing, or deceptive request routing).
    This is most typically seen if an unreachable AirWatch server is entered of if bad credentials are provided.
    These will be returned as `400 Bad Request` with an accompanying exception with more information.

| `404 Not Found`
| The requested resource could not be found but may be available again in the future. Subsequent requests by the client are permissible.
|===


[resources]
= Resources

== AirWatch Cloud Connector
This Status Response resource shows the current status for AirWatch Cloud Connector (ACC)

=== Query ACC

A `GET` request will list the current state for the service.

==== Example Request

include::{snippets}/StatusControllerTest/getAccStatusWhenRequestingShouldReturnStatusResponseSuccess/curl-request.adoc[]

==== Example Response

include::{snippets}/StatusControllerTest/getAccStatusWhenRequestingShouldReturnStatusResponseSuccess/http-response.adoc[]

== Active Directory Status
This Status Response resource shows the current status for AirWatch Cloud Connector (ACC)

=== Query AD

A `GET` request will list the current state for the service.

==== Example Request

include::{snippets}/StatusControllerTest/getAdStatusWhenRequestingShouldReturnStatusResponseSuccess/curl-request.adoc[]

==== Example Response

include::{snippets}/StatusControllerTest/getAdStatusWhenRequestingShouldReturnStatusResponseSuccess/http-response.adoc[]

== Properties

The properties defined in application.properties is exposed as a REST endpoint and can be used to verify that the properties defined are being picked up correctly.

=== Query Properties

A `GET` request will list the properties defined.

==== Example Request

include::{snippets}/PropertiesControllerTest/testPropertiesEndpointAndExpectStatus200Response/curl-request.adoc[]

==== Example Response

include::{snippets}/PropertiesControllerTest/testPropertiesEndpointAndExpectStatus200Response/http-response.adoc[]

Use this to verify that the tenant URL as well as the username provided are correct.

NOTE: The password provided will *not* be serialized so it wont show in the output.


